# Generated by Django 5.1.6 on 2025-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='shareholder_status',
            field=models.CharField(choices=[('OSANIK', 'osanik'), ('ÜKS_ASUTAJATEST', 'üks asutajatests'), ('ASUTAJA', 'asutaja')], max_length=16),
        ),
    ]
