# Generated by Django 5.1.6 on 2025-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_alter_shareholder_shareholder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='shareholder_status',
            field=models.CharField(choices=[('ÜKS_ASUTAJATEST', 'Üks asutajatests'), ('OSANIK', 'Osanik'), ('ASUTAJA', 'Asutaja')], max_length=16),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='shareholder_type',
            field=models.CharField(choices=[('FÜÜSILINE', 'Füüsiline isik'), ('JURIIDILINE', 'Juriidiline isik')], max_length=16),
        ),
    ]
